<%
// styleVarsWizard.inc
// Copyright (c) 2007 - 2010 Citrix Systems, Inc. All Rights Reserved.
// Web Interface 5.4.0.0
%>
<%
    String fontFace = "Segoe UI, Tahoma,Verdana, Helvetica, Arial, sans-serif";
    String fontSizeXSmall = "70%";
    String fontSizeSmall = "90%";
    String fontSizeBase = "100%";
    String fontSizeLarge = "120%";
    String fontSizeXLarge = "130%";
    String brandingColor = "#666699";
    String buttonWidth_Apply_Cancel_Ok = "6em";
%>
