    <title><%=WebUtilities.escapeHTML(wiContext.getWebAbstraction().getQueryStringParameter("Title"))%></title>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta http-equiv="Content-Language" content="<%=wiContext.getCurrentLocale().getLanguage()%>">
    <meta http-equiv="expires" content="0">
    <meta http-equiv="pragma" content="no-cache">
    <meta name="ROBOTS" content="NOINDEX, NOFOLLOW, NOARCHIVE">

