<%
// style.inc
// Copyright (c) 2007 - 2010 Citrix Systems, Inc. All Rights Reserved.
// Web Interface 5.4.0.0

// A collection of styles applied to the site
%>

<!--#include file="fullStyle.inc"-->
<!--#include file="messagesStyle.inc"-->
<!--#include file="navStyle.inc"-->
<!--#include file="settingsStyle.inc"-->
<!--#include file="viewStyle.inc"-->
<!--#include file="lightboxStyle.inc"-->
<!--#include file="wiWizardStyle.inc"-->