BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
GO
ALTER TABLE SMS_CONTACT ADD
	phoneOverrided bit NOT NULL CONSTRAINT DF_SMS_CONTACT_phoneOverrided DEFAULT 0,
	mobileOverrided bit NOT NULL CONSTRAINT DF_SMS_CONTACT_mobileOverrided DEFAULT 0
GO
UPDATE [SMS_CONTACT] SET phoneOverrided=1, mobileOverrided=1
GO
UPDATE [SETTINGS] SET [VALUE] = '2.1.5' WHERE [SETTING] = 'VERSION'
GO
COMMIT
GO