BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
ALTER TABLE [SMS_CONTACT]
	DROP CONSTRAINT DF_SMS_CONTACT_TempPinCode
GO
ALTER TABLE [SMS_CONTACT] ADD CONSTRAINT
	DF_SMS_CONTACT_TempPinCode DEFAULT ((1)) FOR TempPinCode
GO
GO
UPDATE [SETTINGS] SET [VALUE] = '2.2.3' WHERE [SETTING] = 'VERSION'
GO
COMMIT
GO