BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
GO
ALTER TABLE UserSheetCode DROP CONSTRAINT FK_UserSheetCode_UserSheet
GO
ALTER TABLE UserSheetCode ADD CONSTRAINT 
	FK_UserSheetCode_UserSheet FOREIGN KEY 
	( userSheetId ) REFERENCES UserSheet ( id ) ON UPDATE  CASCADE 
	 ON DELETE CASCADE 
GO

CREATE TABLE [HardToken] (
	[id] INT NOT NULL IDENTITY (1, 1),
	[serial] VARCHAR(200) NOT NULL,
	[key] VARCHAR(200) NOT NULL,
	[type] INT NOT NULL DEFAULT 0
)  ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_HardToken_serial] ON [HardToken] 
(
	[Serial] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

UPDATE [SETTINGS] SET [VALUE] = '2.1.9' WHERE [SETTING] = 'VERSION'
GO
COMMIT
GO