/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON

GO
CREATE TABLE UserOathCalc
	(
	id bigint NOT NULL,
	userId bigint NOT NULL,
	config varchar(MAX) NOT NULL,
	configName varchar(30) NOT NULL
	)  ON [PRIMARY]
	 TEXTIMAGE_ON [PRIMARY]
GO
ALTER TABLE UserOathCalc ADD CONSTRAINT
	PK_UserOathCalc PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
CREATE NONCLUSTERED INDEX IX_UserOathCalc_User ON UserOathCalc
	(
	userId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX IX_UserOathCalc_ConfigName ON UserOathCalc
	(
	configName
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_UserOathCalc_User_ConfigName ON UserOathCalc
	(
	userId,
	configName
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE UserOathCalc ADD CONSTRAINT
	FK_UserOathCalc_SMS_CONTACT FOREIGN KEY
	(
	userId
	) REFERENCES SMS_CONTACT
	(
	ID
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO

UPDATE [UserProviders] 
SET [config] = [config] + ',Default'
WHERE [authProviderId] = (SELECT [id] FROM [AuthProviders] WHERE [name] = 'OATHCalc')
GO

UPDATE [SETTINGS] SET [VALUE] = '2.1.2' WHERE [SETTING] = 'VERSION'
GO

COMMIT