BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [AE_KEY_TEST](
	[ENCRYPTED] [varchar](1000) NULL
) ON [PRIMARY]

GO

ALTER TABLE SMS_CONTACT ALTER COLUMN PINCODE VARCHAR(128) NULL
GO

ALTER TABLE SMS_CONTACT ALTER COLUMN PANIC_PINCODE VARCHAR(128) NULL
GO

UPDATE [SETTINGS] SET [VALUE] = '2.4.4' WHERE [SETTING] = 'VERSION'
GO
COMMIT
GO
