SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[UserSheet](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[active] [bit] NOT NULL,
	[userId] [bigint] NOT NULL,
 CONSTRAINT [PK_UserSheet] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[UserSheet]  WITH CHECK ADD  CONSTRAINT [FK_UserSheet_User] FOREIGN KEY([userId])
REFERENCES [dbo].[SMS_CONTACT] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[UserSheet] CHECK CONSTRAINT [FK_UserSheet_User]
GO

ALTER TABLE [dbo].[UserSheet] ADD  CONSTRAINT [DF_UserSheet_active]  DEFAULT ((0)) FOR [active]
GO


GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[UserSheetCode](
	[id] [bigint] IDENTITY(1,1) NOT NULL,
	[userSheetId] [bigint] NOT NULL,
	[col] [int] NOT NULL,
	[row] [int] NOT NULL,
	[code] [varchar](10) NOT NULL,
	[displayed] [bit] NOT NULL,
	[used] [bit] NOT NULL,
 CONSTRAINT [PK_UserSheetCode] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[UserSheetCode]  WITH CHECK ADD  CONSTRAINT [FK_UserSheetCode_UserSheet] FOREIGN KEY([userSheetId])
REFERENCES [dbo].[UserSheet] ([id])
GO

ALTER TABLE [dbo].[UserSheetCode] CHECK CONSTRAINT [FK_UserSheetCode_UserSheet]
GO

ALTER TABLE [dbo].[SMS_CONTACT] ADD PINCODE CHAR(40) NULL DEFAULT ''
GO

ALTER TABLE [dbo].[SMS_LOG] ADD STATE CHAR(10) NOT NULL DEFAULT ''
GO

CREATE NONCLUSTERED INDEX [IX_SMS_LOG_STATE] ON [dbo].[SMS_LOG] 
(
	[STATE] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
GO

UPDATE [dbo].[SETTINGS] SET [VALUE] = '2.0.4' WHERE [SETTING] = 'VERSION'
GO