BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
GO

ALTER TABLE [dbo].[SMS_CONTACT] ADD [LEFT_IMAGE] [nvarchar](1000) NULL
GO

ALTER TABLE [dbo].[SMS_CONTACT] ADD [RIGHT_IMAGE] [nvarchar](1000) NULL
GO

UPDATE [SETTINGS] SET [VALUE] = '2.3.7' WHERE [SETTING] = 'VERSION'
GO
COMMIT
GO
