BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[AE_REPORTING](
	[DATETIME] [datetime] NOT NULL,
	[AE_INSTANCE] [nvarchar](34) NOT NULL
) ON [PRIMARY]

GO

UPDATE [SETTINGS] SET [VALUE] = '2.4.3' WHERE [SETTING] = 'VERSION'
GO
COMMIT
GO
