BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON

GO

ALTER TABLE [SMS_CONTACT] ADD FirstName NVARCHAR(256) NULL
GO
ALTER TABLE [SMS_CONTACT] ADD LastName NVARCHAR(256) NULL
GO

UPDATE [SETTINGS] SET [VALUE] = '2.3.1' WHERE [SETTING] = 'VERSION'
GO

COMMIT