BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON

GO

CREATE TABLE [Vault]
	(
	id int NOT NULL IDENTITY (1, 1),
	content varchar(MAX) NOT NULL,
	userId bigint NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE [Vault] ADD CONSTRAINT
	PK_Vault PRIMARY KEY CLUSTERED 
	(
	id
	)
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_Vault_userId ON [Vault]
	(
	userId
	)
GO
ALTER TABLE [Vault] ADD CONSTRAINT
	FK_Vault_SMS_CONTACT FOREIGN KEY
	(
	userId
	) REFERENCES [SMS_CONTACT]
	(
	ID
	) ON UPDATE  CASCADE
	 ON DELETE  CASCADE 
GO

UPDATE [SETTINGS] SET [VALUE] = '2.3.0' WHERE [SETTING] = 'VERSION'
GO

COMMIT