BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
GO

CREATE TABLE [dbo].[AUTH_IMAGES](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[EXTERNAL_ID] [int] NOT NULL,
	[URL] [nvarchar](1000) NOT NULL,
 CONSTRAINT [PK_AUTH_IMAGE] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

CREATE TABLE [dbo].[AUTH_IMAGE_THUMBNAILS](
	[IMAGE_ID] [bigint] NOT NULL,
	[THUMBNAIL] [varbinary](max) NOT NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

UPDATE [SETTINGS] SET [VALUE] = '2.3.8' WHERE [SETTING] = 'VERSION'
GO
COMMIT
GO
