/****** Object:  Table [dbo].[VALID_IP]    Script Date: 05/23/2012 02:10:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[VALID_IP]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[VALID_IP](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[IP] [nvarchar](15) NOT NULL,
 CONSTRAINT [PK_ValidIP] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [IX_VALID_IP] UNIQUE NONCLUSTERED 
(
	[IP] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET IDENTITY_INSERT [dbo].[VALID_IP] ON
INSERT [dbo].[VALID_IP] ([ID], [IP]) VALUES (1, N'172.27.12.221')
SET IDENTITY_INSERT [dbo].[VALID_IP] OFF
/****** Object:  Table [dbo].[TOKEN_LOG]    Script Date: 05/23/2012 02:10:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[TOKEN_LOG]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[TOKEN_LOG](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[QUANTITY] [bigint] NOT NULL,
	[DATE_INSERTED] [datetime] NOT NULL,
 CONSTRAINT [PK_TOKEN_LOG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[SMS_LOG]    Script Date: 05/23/2012 02:10:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SMS_LOG]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[SMS_LOG](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[AD_USERNAME] [nvarchar](max) NOT NULL,
	[PASSCODE] [nvarchar](max) NOT NULL,
	[CREATION_DATE] [datetime] NOT NULL,
	[DUE_DATE] [datetime] NOT NULL,
 CONSTRAINT [PK_SMS_LOG] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
/****** Object:  Table [dbo].[SMS_CONTACT]    Script Date: 05/23/2012 02:10:22 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SMS_CONTACT]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[SMS_CONTACT](
	[ID] [bigint] IDENTITY(1,1) NOT NULL,
	[AD_USERNAME] [nvarchar](100) NOT NULL,
	[MOBILE_NUMBER] [nvarchar](50) NULL,
	[DISPLAY_NAME] [nvarchar](100) NULL,
	[USER_TYPE] [nvarchar](50) NOT NULL,
	[INPUT_PHONE_NUMBER] [nvarchar](50) NULL,
	[CREATION_DATE] [datetime] NOT NULL,
	[ORG_NAME] [nvarchar](100) NULL,
	[ORG_TYPE] [nvarchar](50) NULL,
	[UPDATE_DATE] [datetime] NULL,
	[USER_STATUS] [varchar](450) NULL,
 CONSTRAINT [PK_SMS_CONTACT] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY],
 CONSTRAINT [UK_SMS_CONTACT] UNIQUE NONCLUSTERED 
(
	[AD_USERNAME] ASC,
	[ORG_NAME] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [dbo].[SETTINGS]    Script Date: 05/23/2012 02:10:24 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[SETTINGS]') AND type in (N'U'))
BEGIN
CREATE TABLE [dbo].[SETTINGS](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[SETTING] [nvarchar](50) NOT NULL,
	[VALUE] [nvarchar](max) NOT NULL,
	[OBJECT] [nvarchar](50) NULL,
 CONSTRAINT [PK_SETTINGS] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO
SET IDENTITY_INSERT [dbo].[SETTINGS] ON
INSERT [dbo].[SETTINGS] ([ID], [SETTING], [VALUE], [OBJECT]) VALUES (1, N'SMS_MSG', N' ', N'SMS_SERVICE')
INSERT [dbo].[SETTINGS] ([ID], [SETTING], [VALUE], [OBJECT]) VALUES (2, N'PASSCODE_LEN', N' ', N'SMS_SERVICE')
INSERT [dbo].[SETTINGS] ([ID], [SETTING], [VALUE], [OBJECT]) VALUES (3, N'VERSION', N'2.0.0', N'AUTHGATEWAY')
SET IDENTITY_INSERT [dbo].[SETTINGS] OFF
/****** Object:  Default [DF_TOKEN_LOG_QUANTITY]    Script Date: 05/23/2012 02:10:22 ******/
IF Not EXISTS (SELECT * FROM sys.default_constraints WHERE object_id = OBJECT_ID(N'[dbo].[DF_TOKEN_LOG_QUANTITY]') AND parent_object_id = OBJECT_ID(N'[dbo].[TOKEN_LOG]'))
Begin
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_TOKEN_LOG_QUANTITY]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TOKEN_LOG] ADD  CONSTRAINT [DF_TOKEN_LOG_QUANTITY]  DEFAULT ((0)) FOR [QUANTITY]
END


End
GO
/****** Object:  Default [DF_TOKEN_LOG_DATE_INSERTED]    Script Date: 05/23/2012 02:10:22 ******/
IF Not EXISTS (SELECT * FROM sys.default_constraints WHERE object_id = OBJECT_ID(N'[dbo].[DF_TOKEN_LOG_DATE_INSERTED]') AND parent_object_id = OBJECT_ID(N'[dbo].[TOKEN_LOG]'))
Begin
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_TOKEN_LOG_DATE_INSERTED]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[TOKEN_LOG] ADD  CONSTRAINT [DF_TOKEN_LOG_DATE_INSERTED]  DEFAULT (getdate()) FOR [DATE_INSERTED]
END


End
GO
/****** Object:  Default [DF_SMS_LOG_CREATION_DATE]    Script Date: 05/23/2012 02:10:22 ******/
IF Not EXISTS (SELECT * FROM sys.default_constraints WHERE object_id = OBJECT_ID(N'[dbo].[DF_SMS_LOG_CREATION_DATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[SMS_LOG]'))
Begin
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_SMS_LOG_CREATION_DATE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SMS_LOG] ADD  CONSTRAINT [DF_SMS_LOG_CREATION_DATE]  DEFAULT (getdate()) FOR [CREATION_DATE]
END


End
GO
/****** Object:  Default [DF_SMS_LOG_DUE_DATE]    Script Date: 05/23/2012 02:10:22 ******/
IF Not EXISTS (SELECT * FROM sys.default_constraints WHERE object_id = OBJECT_ID(N'[dbo].[DF_SMS_LOG_DUE_DATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[SMS_LOG]'))
Begin
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_SMS_LOG_DUE_DATE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SMS_LOG] ADD  CONSTRAINT [DF_SMS_LOG_DUE_DATE]  DEFAULT (dateadd(minute,(15),getdate())) FOR [DUE_DATE]
END


End
GO
/****** Object:  Default [DF_SMS_CONTACT_USER_TYPE]    Script Date: 05/23/2012 02:10:22 ******/
IF Not EXISTS (SELECT * FROM sys.default_constraints WHERE object_id = OBJECT_ID(N'[dbo].[DF_SMS_CONTACT_USER_TYPE]') AND parent_object_id = OBJECT_ID(N'[dbo].[SMS_CONTACT]'))
Begin
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_SMS_CONTACT_USER_TYPE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SMS_CONTACT] ADD  CONSTRAINT [DF_SMS_CONTACT_USER_TYPE]  DEFAULT (user_name()) FOR [USER_TYPE]
END


End
GO
/****** Object:  Default [DF_SMS_CONTACT_CREATION_DATE]    Script Date: 05/23/2012 02:10:22 ******/
IF Not EXISTS (SELECT * FROM sys.default_constraints WHERE object_id = OBJECT_ID(N'[dbo].[DF_SMS_CONTACT_CREATION_DATE]') AND parent_object_id = OBJECT_ID(N'[dbo].[SMS_CONTACT]'))
Begin
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_SMS_CONTACT_CREATION_DATE]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SMS_CONTACT] ADD  CONSTRAINT [DF_SMS_CONTACT_CREATION_DATE]  DEFAULT (getdate()) FOR [CREATION_DATE]
END


End
GO
/****** Object:  Default [DF_SMS_CONTACT_USER_STATUS]    Script Date: 05/23/2012 02:10:22 ******/
IF Not EXISTS (SELECT * FROM sys.default_constraints WHERE object_id = OBJECT_ID(N'[dbo].[DF_SMS_CONTACT_USER_STATUS]') AND parent_object_id = OBJECT_ID(N'[dbo].[SMS_CONTACT]'))
Begin
IF NOT EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_SMS_CONTACT_USER_STATUS]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[SMS_CONTACT] ADD  CONSTRAINT [DF_SMS_CONTACT_USER_STATUS]  DEFAULT ('False') FOR [USER_STATUS]
END


End
GO
