/* To prevent any potential data loss issues, you should review this script in detail before running it outside the context of the database designer.*/
BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
GO
CREATE TABLE [UserAdmin]
	(
	id int NOT NULL IDENTITY (1, 1),
	sid varchar(184) NOT NULL,
	userId bigint NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE [UserAdmin] ADD CONSTRAINT
	PK_UserAdmin PRIMARY KEY CLUSTERED 
	(
	id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
CREATE UNIQUE NONCLUSTERED INDEX IX_UserAdmin_userId ON [UserAdmin]
	(
	userId
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
CREATE UNIQUE NONCLUSTERED INDEX IX_UserAdmin_SID ON [UserAdmin]
	(
	sid
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
ALTER TABLE [UserAdmin] ADD CONSTRAINT
	FK_UserAdmin_SMS_CONTACT FOREIGN KEY
	(
	userId
	) REFERENCES [SMS_CONTACT]
	(
	ID
	) ON UPDATE  CASCADE
	 ON DELETE  CASCADE 
	
GO
UPDATE [SETTINGS] SET [VALUE] = '2.1.3' WHERE [SETTING] = 'VERSION'
GO
COMMIT
GO