BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON

GO

INSERT [dbo].[AuthProviders] ([name]) VALUES (N'Passthrough');
GO

UPDATE [SETTINGS] SET [VALUE] = '2.2.9' WHERE [SETTING] = 'VERSION'
GO

COMMIT