BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
INSERT [dbo].[AuthProviders] ([name]) VALUES (N'Email');
GO
ALTER TABLE dbo.SMS_CONTACT ADD
	email varchar(255) NULL
GO
UPDATE [dbo].[SETTINGS] SET [VALUE] = '2.0.8' WHERE [SETTING] = 'VERSION'
GO
COMMIT